version: '3'
services:
  app:
    image: variacode/demo-webapp
    ports:
      - 8080:8080
    command: java -jar demo-webapp.jar
#    volumes:
#      - ${GLEN_JAR:-./build/libs/glen-market-maker.jar}:/var/app/glen-market-maker.jar
#      - ./config:/var/app/config
#      - ./logs:/var/app/logs
    working_dir: /var/app
#    environment:
